import localFont from "next/font/local";
import "./globals.css";
import { Public_Sans } from "next/font/google";
import StoreProvider from "@/lib/storeProvider";
import Sidebar from "@/app/components/Sidebar";

const publicSans = Public_Sans({
  weight: ["400", "700", "500"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={`${publicSans.className}`}>
          <div className="flex test">
            <Sidebar />
            <div className="flex-1 ">{children}</div>
          </div>
        </body>
      </StoreProvider>
    </html>
  );
}
